In [2]:
import pandas as pd
import numpy as numpy

df=pd.read_csv("Astram event data_anonymized - Astram event data_anonymizedb40ac87.csv");
df.head(1)

,id,event_type,latitude,longitude,endlatitude,endlongitude,address,end_address,event_cause,requires_road_closure,...,resolved_at_address,resolved_at_latitude,resolved_at_longitude,closed_by_id,closed_datetime,resolved_by_id,resolved_datetime,gba_identifier,zone,junction
0,FKID000000,unplanned,13.040004,77.518099,0.0,0.0,"Mumbai Bengaluru Highway, Jalahalli Cross Junc...",NaN,vehicle_breakdown,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Column Cleaning -> Discarding unwanted column

In [3]:
#Droping unwanted coloumns
df.drop(['id',
'client_id',
'created_by_id',
'last_modified_by_id',
'assigned_to_police_id',
'citizen_accident_id',
'kgid', 
'closed_by_id',
'resolved_by_id',
'gba_identifier',
'veh_no',
'authenticated',
'map_file',    
'route_path',
'meta_data',
'comment',
'reason_breakdown',
'cargo_material',
'age_of_truck',
'veh_type',
'resolved_at_latitude', 'resolved_at_longitude','resolved_at_address','modified_datetime'], axis=1, inplace=True)

df.head(5)

,event_type,latitude,longitude,endlatitude,endlongitude,address,end_address,event_cause,requires_road_closure,start_datetime,...,direction,description,corridor,priority,created_date,police_station,closed_datetime,resolved_datetime,zone,junction
0,unplanned,13.040004,77.518099,0.000000,0.000000,"Mumbai Bengaluru Highway, Jalahalli Cross Junc...",NaN,vehicle_breakdown,False,2024-03-07 17:01:48.111+00,...,NaN,s m circle in coming man track,Tumkur Road,High,2024-03-07 17:03:51.164032+00,Peenya,NaN,NaN,NaN,NaN
1,unplanned,12.921876,77.645158,0.000000,0.000000,"19th Main Road, Heavie Halcyon, Agara, HSR Lay...",NaN,vehicle_breakdown,False,2024-01-30 04:07:24.173+00,...,NaN,Starting problem,ORR East 1,High,2024-01-30 04:08:22.954979+00,HSR Layout,NaN,2024-01-30 04:17:46.828355+00,NaN,NaN
2,unplanned,12.955622,77.585708,0.000000,0.000000,"Lalbagh Main Road, Dr Sri Shantaveera Swami Ci...",NaN,others,False,2023-11-11 06:18:03.343+00,...,NaN,ಊರ್ವಶಿ ಜಂಕ್ಷನ್ ನಲ್ಲಿ ಒಳಚರಂಡಿ ಚೇಂಬರ್ ಗೆ ಹೊಸದಾಗಿ...,Non-corridor,Low,2023-11-11 06:20:00.989398+00,Wilson Garden,2024-01-30 04:56:03.281509+00,NaN,Central Zone 2,UrvashiJunction
3,unplanned,13.006147,77.579435,13.006239,77.579516,"Sankey Road, Bashyam Circle, Sadashiva Nagar, ...","Sankey Road, Palace Orchard Upper, Sadashiva N...",tree_fall,True,2024-03-07 17:56:55.061+00,...,NaN,tree fall,Non-corridor,Low,2024-03-07 17:58:56.696892+00,Sadashivanagar,2024-03-14 07:42:05.54944+00,NaN,NaN,NaN
4,unplanned,12.953980,77.585233,0.000000,0.000000,"Lalbagh Fort Road, Lalbagh Main Gate Junction,...",NaN,vehicle_breakdown,False,2024-01-30 04:56:32.348+00,...,NaN,[LOCATION] ಪೈಪ್ [PERSON] ವಾಹನ ಆಫ್ ಆಗಿರುತ್ತದೆ ಸರ್,Non-corridor,Low,2024-01-30 04:58:55.937662+00,Wilson Garden,2024-01-30 05:35:17.338283+00,NaN,NaN,LalbaghMainGateJunc

In [4]:
df.columns = df.columns.str.strip()

ordered_columns = [
    'event_type',
    'event_cause',
    'description',
    'requires_road_closure',
    'status',
    'priority',
    'start_datetime',
    'end_datetime',
    'created_date',
    'closed_datetime',
    'resolved_datetime',
    'latitude',
    'longitude',
    'endlatitude',
    'endlongitude',
    'end_address',
    'address',
    'corridor',
    'junction',
    'zone',
    'direction',
    'police_station'
]

# 3. Reorder the DataFrame
df = df[ordered_columns]

df.head(2)

,event_type,event_cause,description,requires_road_closure,status,priority,start_datetime,end_datetime,created_date,closed_datetime,...,longitude,endlatitude,endlongitude,end_address,address,corridor,junction,zone,direction,police_station
0,unplanned,vehicle_breakdown,s m circle in coming man track,False,closed,High,2024-03-07 17:01:48.111+00,NaN,2024-03-07 17:03:51.164032+00,NaN,...,77.518099,0.0,0.0,NaN,"Mumbai Bengaluru Highway, Jalahalli Cross Junc...",Tumkur Road,NaN,NaN,NaN,Peenya
1,unplanned,vehicle_breakdown,Starting problem,False,resolved,High,2024-01-30 04:07:24.173+00,NaN,2024-01-30 04:08:22.954979+00,NaN,...,77.645158,0.0,0.0,NaN,"19th Main Road, Heavie Halcyon, Agara, HSR Lay...",ORR East 1,NaN,NaN,NaN,HSR Layout

In [5]:
for col in df.columns:
    print(col)

event_type
event_cause
description
requires_road_closure
status
priority
start_datetime
end_datetime
created_date
closed_datetime
resolved_datetime
latitude
longitude
endlatitude
endlongitude
end_address
address
corridor
junction
zone
direction
police_station

In [6]:
#Writing the cleaned data to a new csv file
df.to_csv("cleaned_astram_event_data.csv", index=False)

Moving Forward

In [7]:
df_master=df.copy()

event_causes = [
    'construction',
    'public_event',
    'procession',
    'vip_movement',
    'protest'
]

df_events = df[
    df['event_cause'].isin(event_causes)
].copy()

print(df_master.shape)
print(df_events.shape)


df_events.head(5)

(8173, 22)
(671, 22)

,event_type,event_cause,description,requires_road_closure,status,priority,start_datetime,end_datetime,created_date,closed_datetime,...,longitude,endlatitude,endlongitude,end_address,address,corridor,junction,zone,direction,police_station
8,planned,public_event,"Cricket Match at M Chinnaswamy Satdium, [LOCAT...",False,closed,High,2024-02-12 02:05:46+00,2024-02-12 14:05:46+00,2024-01-30 05:09:41.077868+00,NaN,...,77.599537,NaN,NaN,NaN,"ಲಿಂಕ್ ರಸ್ತೆ, ಅಶೋಕನಗರ, ಬೆಂಗಳೂರು ಮಧ್ಯ ನಗರ ನಿಗಮ, ...",CBD 2,QueensStatueCircle,NaN,NaN,Cubbon Park
40,planned,construction,[LOCATION] works going on sir,False,closed,High,2024-01-30 11:31:12.848+00,2024-01-30 11:31:46+00,2024-01-30 11:32:15.765069+00,NaN,...,77.698675,0.000000,0.000000,NaN,"Outer Ring Road, Sumadhura Platinum Square, Ka...",ORR East 1,NaN,NaN,NaN,HAL Old Airport
45,planned,construction,NaN,True,closed,Low,2024-01-30 21:21:10.303+00,2024-01-30 21:20:46+00,2024-01-30 21:21:41.722681+00,NaN,...,77.613150,13.008551,77.613128,"Shampura Main Road, AK Colony, Devarajeevana H...","Shampura Main Road, AK Colony, Devarajeevana H...",Non-corridor,NaN,NaN,NaN,K.G. Halli
52,planned,construction,[LOCATION] towards marathhalli and karthiknaga...,False,closed,High,2024-01-30 20:56:01.732+00,2024-01-31 09:05:46+00,2024-01-30 20:56:43.100304+00,NaN,...,77.700635,0.000000,0.000000,NaN,"Outer Ring Road, Karthik Nagar, Marathahalli, ...",ORR East 2,NaN,NaN,NaN,HAL Old Airport
82,planned,construction,karthiknagara towards [LOCATION] and karthikna...,False,closed,High,2024-03-07 21:23:16.629+00,2024-03-08 10:05:46+00,2024-03-07 21:25:40.927133+00,NaN,...,77.700653,0.000000,0.000000,NaN,"Outer Ring Road, Karthik Nagar, Marathahalli, ...",ORR East 2,NaN,NaN,NaN,HAL Old Airport

In [8]:
print(df_master['requires_road_closure'].value_counts(dropna=False))

print(df_master['priority'].value_counts(dropna=False))

print(df_master['status'].value_counts(dropna=False))

requires_road_closure
False    7497
True      676
Name: count, dtype: int64
priority
High    5030
Low     3141
NaN        2
Name: count, dtype: int64
status
closed      7095
active      1007
resolved      71
Name: count, dtype: int64

Priority ->Very usable.

Road Closure ->About 8.3% of incidents require closure.
The classes are imbalanced, but not so extreme that the target is useless.

Status -> Mostly reflects workflow progression (closed/active/resolved).
Not a useful prediction target for your problem.

Next Task : Understand the Event Dataset

In [9]:
print(df_events['requires_road_closure'].value_counts(dropna=False))

print(df_events['priority'].value_counts(dropna=False))

print(df_master['event_cause'].value_counts(dropna=False))

requires_road_closure
False    464
True     207
Name: count, dtype: int64
priority
High    380
Low     291
Name: count, dtype: int64
event_cause
vehicle_breakdown       4896
others                   638
pot_holes                537
construction             480
water_logging            458
accident                 365
tree_fall                284
road_conditions          170
congestion               136
public_event              84
procession                72
vip_movement              20
protest                   15
Debris                    12
test_demo                  3
Fog / Low Visibility       2
debris                     1
Name: count, dtype: int64

In [10]:
df_events['start_datetime'] = pd.to_datetime(df_events['start_datetime'], errors='coerce', format='mixed').dt.tz_localize(None)
df_events['end_datetime'] = pd.to_datetime(df_events['end_datetime'], errors='coerce', format='mixed').dt.tz_localize(None)

# 3. Recalculate your true error count now
actual_start_errors = df_events.loc[df_events['start_datetime'].isna() & df['start_datetime'].notna()]
actual_end_errors = df_events.loc[df_events['end_datetime'].isna() & df['end_datetime'].notna()]

print(f"Actual text formatting errors (Start): {len(actual_start_errors)}")
print(f"Actual text formatting errors (End): {len(actual_end_errors)}")

# 4. Calculate your duration metric safely
df_events['duration_hours'] = (df_events['end_datetime'] - df_events['start_datetime']) / pd.Timedelta(hours=1)

df_events['duration_hours'].describe()

Actual text formatting errors (Start): 0
Actual text formatting errors (End): 0

count      466.000000
mean       278.201606
std       2320.278389
min        -55.499988
25%          0.117620
50%          6.948788
75%         16.999455
max      34184.320343
Name: duration_hours, dtype: float64

In [11]:
# Count negative durations
negative_durations = df_events[df_events['duration_hours'] < 0]
print(f"Number of rows with negative duration: {len(negative_durations)}")

# Display the problematic rows to investigate
negative_durations[['start_datetime', 'end_datetime', 'duration_hours','event_cause']].head()

Number of rows with negative duration: 57

,start_datetime,end_datetime,duration_hours,event_cause
45,2024-01-30 21:21:10.303,2024-01-30 21:20:46.000,-0.006751,construction
158,2024-01-31 22:25:30.936,2024-01-31 18:26:46.000,-3.979149,construction
375,2024-02-03 21:28:38.926,2024-02-03 12:20:46.000,-9.131368,construction
490,2024-02-05 11:23:01.315,2024-02-04 17:25:46.000,-17.954254,construction
1064,2024-02-14 22:05:46.000,2024-02-13 05:22:20.357,-40.723790,public_event

In [12]:
#check the category of negative value grouped with event cause
negative_summary = negative_durations.groupby('event_cause')['duration_hours'].agg(['count', 'min', 'max'])
print(negative_summary)

              count        min        max
event_cause
construction     36 -55.499988  -0.000796
procession        5 -10.999142  -2.952920
public_event      9 -40.723790  -0.001584
vip_movement      7 -42.999963 -24.524401

In [13]:
# Define the thresholds in hours
durations = {
    "24 hours": 24,
    "7 days": 7 * 24,
    "30 days": 30 * 24,
    "365 days": 365 * 24
}

# Calculate and print counts without inspecting rows
for label, hours in durations.items():
    count = (df_events['duration_hours'] > hours).sum()
    print(f"Events longer than {label}: {count}")

Events longer than 24 hours: 102
Events longer than 7 days: 48
Events longer than 30 days: 22
Events longer than 365 days: 3

In [14]:
# Filter for durations greater than 365 days and select specific columns
columns_to_show = ['event_cause', 'start_datetime', 'end_datetime', 'duration_hours', 'status', 'priority']
df_long_events = df_events.loc[df_events['duration_hours'] > (365 * 24), columns_to_show]

# Display the 3 records
df_long_events

,event_cause,start_datetime,end_datetime,duration_hours,status,priority
6647,construction,2023-12-09 00:05:46.000,2026-11-09 11:35:46,25595.500000,active,Low
6648,construction,2023-12-09 00:05:46.000,2026-11-09 11:35:46,25595.500000,active,Low
6894,construction,2023-12-16 03:16:32.764,2027-11-09 11:35:46,34184.320343,active,High

In [15]:
long_events = df_events[df_events['duration_hours'] > 720]
long_events['event_cause'].value_counts()

event_cause
construction    21
public_event     1
Name: count, dtype: int64

In [16]:
df_events.drop(['start_datetime', 'end_datetime', 'duration_hours'], axis=1, inplace=True )

In [17]:
df_events.isnull().sum()

df_events.drop(['resolved_datetime',
'closed_datetime',
'direction',
'end_address'],axis=1, inplace=True)

In [18]:
df_events.isnull().sum()
print(f"unique junctions: {df_events['junction'].nunique()}")
print(f"unique zones: {df_events['zone'].nunique()}")
print(f"Value count of zones: {df_events['zone'].value_counts()}")
print(f"Value count of junctions: {df_events['junction'].value_counts().head(10)}")

#decided to drop the junction column

unique junctions: 91
unique zones: 10
Value count of zones: zone
North Zone 1      69
East Zone 1       62
Central Zone 2    35
North Zone 2      29
Central Zone 1    27
East Zone 2       26
South Zone 2      24
West Zone 1       22
West Zone 2       15
South Zone 1      14
Name: count, dtype: int64
Value count of junctions: junction
VeerannapalyaJunction(BEL,HO)    13
SantheCircle                      6
Nagavara-ORR Junction             6
HebbalFlyoverJunc                 6
HoramavuJunction                  5
SadahalliGateJunc(AirportRd)      5
SubbannaJunction                  4
SilkBoardJunc                     4
Marigowda-TavarkereRdJunc         4
HennurRd-DavisRdJunction          4
Name: count, dtype: int64

In [19]:
df_events.drop(['junction'], axis=1, inplace=True)
df_events.isnull().sum()

event_type                 0
event_cause                0
description               31
requires_road_closure      0
status                     0
priority                   0
created_date               0
latitude                   0
longitude                  0
endlatitude               27
endlongitude              27
address                    1
corridor                   0
zone                     348
police_station             0
dtype: int64

In [20]:
columns_check=['police_station','latitude', 'longitude','corridor']
null_counts=df_events[df_events['zone'].isnull()][columns_check].isnull().sum()
print(null_counts)

police_station    0
latitude          0
longitude         0
corridor          0
dtype: int64

In [21]:
pd.crosstab(df_events['police_station'], df_events['zone'])

#Decision:zone is a strong value.The null can also be filled with the police station value. The null values in the zone column can be filled with the corresponding police station value. This is because each police station is associated with a specific zone, and therefore, if the zone information is missing for an event, it can be inferred from the police station that handled the event. This approach helps to maintain data integrity and ensures that all events have a valid zone classification, which is important for analysis and reporting purposes.

zone,Central Zone 1,Central Zone 2,East Zone 1,East Zone 2,North Zone 1,North Zone 2,South Zone 1,South Zone 2,West Zone 1,West Zone 2
police_station,,,,,,,,,,
Adugodi,1,0,0,0,0,0,0,3,0,0
Ashok Nagar,8,0,0,0,0,0,0,0,0,0
Banashankari,0,0,0,0,0,0,0,0,2,0
Banaswadi,13,0,0,2,1,0,0,0,0,0
Bellandur,0,0,1,0,0,0,0,3,0,0
Byatarayanapura,0,0,0,0,0,0,0,0,0,1
Chamarajpet,0,2,0,0,0,0,0,0,0,0
City Market,0,2,0,0,0,0,0,0,0,0
Cubbon Park,2,3,0,0,0,0,0,0,0,0
HAL Old Airport,0,0,54,1,0,0,0,0,0,0
HSR Layout,0,0,0,0,0,0,0,4,0,0
Halasur,1,0,0,0,0,0,0,0,0,0
Halasuru Gate,0,6,0,0,0,0,0,0,0,0
Hebbala,0,0,0,0,12,1,0,0,0,0
Hennuru,0,0,0,21,23,1,0,0,0,0
High ground,0,7,0,0,0,0,0,0,0,0
J.P. Nagar,0,0,0,0,0,0,2,2,0,0
Jalahalli,0,0,0,0,4,3,0,0,0,0
Jayanagara,0,0,0,0,0,0,3,0,0,0
Jeevanbheemanagar,2,0,0,0,0,0,0,0,0,0
Jnanabharathi,0,0,0,0,0,0,0,0,3,0
K.G. Halli,0,0,0,0,13,0,0,0,0,0
K.S. Layout,0,0,0,0,0,0,3,0,1,0
Kamakshipalya,0,0,0,0,0,0,0,0,11,2
Kengeri,0,0,0,0,0,0,0,0,1,0
Kodigehalli,0,0,0,0,9,6,0,0,0,1
Madiwala,0,0,0,0,0,0,0,2,0,0
Magadi Road,0,6,0,0,0,0,0,0,0,2
Mahadevapura,0,0,1,2,0,0,0,0,0,0
Malleshwaram,0,1,0,0,0,0,0,0,0,2
Mico Layout,0,0,0,0,0,0,1,10,0,0
No Police Station,0,0,0,0,0,0,0,0,1,0
Peenya,0,0,0,0,0,0,0,0,1,0
Pulikeshinagar(F.Town),0,0,0,0,4,0,0,0,0,0
Rajajinagar,0,0,0,0,0,0,0,0,1,2
Sadashivanagar,0,0,0,0,0,0,0,0,0,2
Sheshadripuram,0,5,0,0,0,0,0,0,0,0
Thalagattapura,0,0,0,0,0,0,5,0,0,0
Upparpet,0,2,0,0,0,0,0,0,0,0
Vijayanagara,0,0,0,0,0,0,0,0,0,2
Whitefield,0,0,6,0,0,0,0,0,0,0
Wilson Garden,0,1,0,0,0,0,0,0,0,0
Yelahanka,0,0,0,0,3,17,0,0,0,0
Yeshwanthpura,0,0,0,0,0,1,0,0,1,1

In [22]:
missing_values=df_events[df_events['endlatitude'].isnull() | df_events['endlongitude'].isnull()]
print(missing_values['requires_road_closure'].value_counts(dropna=False))

requires_road_closure
False    27
Name: count, dtype: int64

In [23]:
missing_description = df_events[df_events['description'].isnull()]
print(missing_description['event_cause'].value_counts(dropna=False))

missing_address = df_events[df_events['address'].isnull()]
print(missing_address['event_cause'].value_counts(dropna=False))
print(missing_address['latitude'].value_counts(dropna=False))
print(missing_address['longitude'].value_counts(dropna=False))

event_cause
construction    19
public_event     6
protest          3
procession       3
Name: count, dtype: int64
event_cause
construction    1
Name: count, dtype: int64
latitude
13.041611    1
Name: count, dtype: int64
longitude
77.611869    1
Name: count, dtype: int64

In [24]:
df_events.shape

(671, 15)

Decision:zone → keep
endlatitude / endlongitude → keep
description → keep
address → keep

Operation on remaining null values

In [25]:
inconsistent_stations = df_events.groupby('police_station')['zone'].nunique()
print("Stations with multiple zones:\n", inconsistent_stations[inconsistent_stations > 1])

Stations with multiple zones:
 police_station
Adugodi            2
Banaswadi          3
Bellandur          2
Cubbon Park        2
HAL Old Airport    2
Hebbala            2
Hennuru            3
J.P. Nagar         2
Jalahalli          2
K.S. Layout        2
Kamakshipalya      2
Kodigehalli        3
Magadi Road        2
Mahadevapura       2
Malleshwaram       2
Mico Layout        2
Rajajinagar        2
Yelahanka          2
Yeshwanthpura      3
Name: zone, dtype: int64

In [26]:
inconsistent_list = inconsistent_stations[inconsistent_stations > 1].index

df_filtered = df_events[df_events['police_station'].isin(inconsistent_list)]

freq_table = pd.crosstab(df_filtered['police_station'], df_filtered['zone'])

print(freq_table.loc[:, (freq_table != 0).any(axis=0)])

zone             Central Zone 1  Central Zone 2  East Zone 1  East Zone 2  \
police_station
Adugodi                       1               0            0            0
Banaswadi                    13               0            0            2
Bellandur                     0               0            1            0
Cubbon Park                   2               3            0            0
HAL Old Airport               0               0           54            1
Hebbala                       0               0            0            0
Hennuru                       0               0            0           21
J.P. Nagar                    0               0            0            0
Jalahalli                     0               0            0            0
K.S. Layout                   0               0            0            0
Kamakshipalya                 0               0            0            0
Kodigehalli                   0               0            0            0
Magadi Road                   0               6            0            0
Mahadevapura                  0               0            1            2
Malleshwaram                  0               1            0            0
Mico Layout                   0               0            0            0
Rajajinagar                   0               0            0            0
Yelahanka                     0               0            0            0
Yeshwanthpura                 0               0            0            0

zone             North Zone 1  North Zone 2  South Zone 1  South Zone 2  \
police_station
Adugodi                     0             0             0             3
Banaswadi                   1             0             0             0
Bellandur                   0             0             0             3
Cubbon Park                 0             0             0             0
HAL Old Airport             0             0             0             0
Hebbala                    12             1             0             0
Hennuru                    23             1             0             0
J.P. Nagar                  0             0             2             2
Jalahalli                   4             3             0             0
K.S. Layout                 0             0             3             0
Kamakshipalya               0             0             0             0
Kodigehalli                 9             6             0             0
Magadi Road                 0             0             0             0
Mahadevapura                0             0             0             0
Malleshwaram                0             0             0             0
Mico Layout                 0             0             1            10
Rajajinagar                 0             0             0             0
Yelahanka                   3            17             0             0
Yeshwanthpura               0             1             0             0

zone             West Zone 1  West Zone 2
police_station
Adugodi                    0            0
Banaswadi                  0            0
Bellandur                  0            0
Cubbon Park                0            0
HAL Old Airport            0            0
Hebbala                    0            0
Hennuru                    0            0
J.P. Nagar                 0            0
Jalahalli                  0            0
K.S. Layout                1            0
Kamakshipalya             11            2
Kodigehalli                0            1
Magadi Road                0            2
Mahadevapura               0            0
Malleshwaram               0            2
Mico Layout                0            0
Rajajinagar                1            2
Yelahanka                  0            0
Yeshwanthpura              1            1

In [27]:
null_zone_df = df_events[df_events['zone'].isnull()]

null_station_counts = null_zone_df['police_station'].value_counts()

print("Top police stations with missing zones:\n", null_station_counts)

Top police stations with missing zones:
 police_station
HAL Old Airport           89
Hennuru                   28
No Police Station         22
Chikkajala                17
Bellandur                 10
Kodigehalli               10
Yelahanka                 10
Cubbon Park                9
R.T. Nagar                 9
Whitefield                 9
Ashok Nagar                8
Banaswadi                  7
Hebbala                    6
K.R. Pura                  6
Chamarajpet                6
Shivajinagar               6
Yeshwanthpura              6
Kamakshipalya              6
Mico Layout                6
K.G. Halli                 5
Kengeri                    5
Madiwala                   5
K.S. Layout                5
Mahadevapura               4
Thalagattapura             4
Chikkabanavara             3
Halasuru Gate              3
Electronic City            3
Jayanagara                 3
Halasur                    3
Malleshwaram               3
Adugodi                    3
City Market                2
J.P. Nagar                 2
V.V.Puram (C.Pet)          2
Pulikeshinagar(F.Town)     2
Peenya                     2
Vijayanagara               2
Jeevanbheemanagar          2
Sadashivanagar             2
Rajajinagar                2
Basavanagudi               2
HSR Layout                 1
Hulimavu                   1
High ground                1
Byatarayanapura            1
Upparpet                   1
Jalahalli                  1
Devanahalli Airport        1
Banashankari               1
Sheshadripuram             1
Name: count, dtype: int64

In [28]:
df_valid = df_events[df_events['zone'].notnull()]

mode_zone_df = (
    df_valid.groupby('police_station')['zone']
    .apply(lambda x: x.value_counts().head(1))
    .reset_index()
)

mode_zone_df.columns = ['police_station', 'most_frequent_zone', 'count']

print(mode_zone_df)

            police_station most_frequent_zone  count
0                  Adugodi       South Zone 2      3
1              Ashok Nagar     Central Zone 1      8
2             Banashankari        West Zone 1      2
3                Banaswadi     Central Zone 1     13
4                Bellandur       South Zone 2      3
5          Byatarayanapura        West Zone 2      1
6              Chamarajpet     Central Zone 2      2
7              City Market     Central Zone 2      2
8              Cubbon Park     Central Zone 2      3
9          HAL Old Airport        East Zone 1     54
10              HSR Layout       South Zone 2      4
11                 Halasur     Central Zone 1      1
12           Halasuru Gate     Central Zone 2      6
13                 Hebbala       North Zone 1     12
14                 Hennuru       North Zone 1     23
15             High ground     Central Zone 2      7
16              J.P. Nagar       South Zone 2      2
17               Jalahalli       North Zone 1      4
18              Jayanagara       South Zone 1      3
19       Jeevanbheemanagar     Central Zone 1      2
20           Jnanabharathi        West Zone 1      3
21              K.G. Halli       North Zone 1     13
22             K.S. Layout       South Zone 1      3
23           Kamakshipalya        West Zone 1     11
24                 Kengeri        West Zone 1      1
25             Kodigehalli       North Zone 1      9
26                Madiwala       South Zone 2      2
27             Magadi Road     Central Zone 2      6
28            Mahadevapura        East Zone 2      2
29            Malleshwaram        West Zone 2      2
30             Mico Layout       South Zone 2     10
31       No Police Station        West Zone 1      1
32                  Peenya        West Zone 1      1
33  Pulikeshinagar(F.Town)       North Zone 1      4
34             Rajajinagar        West Zone 2      2
35          Sadashivanagar        West Zone 2      2
36          Sheshadripuram     Central Zone 2      5
37          Thalagattapura       South Zone 1      5
38                Upparpet     Central Zone 2      2
39            Vijayanagara        West Zone 2      2
40              Whitefield        East Zone 1      6
41           Wilson Garden     Central Zone 2      1
42               Yelahanka       North Zone 2     17
43           Yeshwanthpura       North Zone 2      1

In [29]:
#To see how many of the 348 missing zones can be recovered

mode_mapping = mode_zone_df.set_index('police_station')['most_frequent_zone'].to_dict()

missing_stations = df_events[df_events['zone'].isnull()]['police_station']

can_recover = missing_stations.isin(mode_mapping.keys())
recoverable_count = can_recover.sum()
unrecoverable_count = (~can_recover).sum()

print(f"--- Missing Zone Recovery Audit ---")
print(f"Total missing rows      : {len(missing_stations)}")
print(f"Successfully recovered  : {recoverable_count}")
print(f"Remaining completely null: {unrecoverable_count}")

# List any stations that cannot be recovered (if any)
if unrecoverable_count > 0:
    print("\nThese stations have NO valid zone data anywhere in the dataset:")
    print(missing_stations[~can_recover].unique())

--- Missing Zone Recovery Audit ---
Total missing rows      : 348
Successfully recovered  : 298
Remaining completely null: 50

These stations have NO valid zone data anywhere in the dataset:
<StringArray>
[     'Chikkabanavara',          'Chikkajala',           'K.R. Pura',
   'V.V.Puram (C.Pet)',          'R.T. Nagar',        'Shivajinagar',
     'Electronic City',            'Hulimavu',        'Basavanagudi',
 'Devanahalli Airport']
Length: 10, dtype: str

In [30]:
check_stations = ['HAL Old Airport', 'Hennuru', 'Yelahanka', 'Bellandur', 'Whitefield']

sanity_check_df = mode_zone_df[mode_zone_df['police_station'].isin(check_stations)]

print("--- Imputation Sanity Check ---")
print(sanity_check_df.to_string(index=False))

--- Imputation Sanity Check ---
 police_station most_frequent_zone  count
      Bellandur       South Zone 2      3
HAL Old Airport        East Zone 1     54
        Hennuru       North Zone 1     23
     Whitefield        East Zone 1      6
      Yelahanka       North Zone 2     17

In [31]:
#fill 298 recoverable missing zones with the most frequent zone for each police station
mode_mapping = mode_zone_df.set_index('police_station')['most_frequent_zone'].to_dict()

df_events['zone'] = df_events['zone'].fillna(df_events['police_station'].map(mode_mapping))

remaining_nulls = df_events['zone'].isnull().sum()
print(f"Imputation done! Remaining nulls in zone: {remaining_nulls}")

Imputation done! Remaining nulls in zone: 50

Analysis and operation on missing description values.

In [32]:
df_events['description_missing'] = df_events['description'].isna()

print("--- Road Closure vs Description Missingness ---")
road_closure_audit = pd.crosstab(
    df_events['requires_road_closure'], 
    df_events['description_missing'], 
    normalize='columns'  
) * 100
print(road_closure_audit)

print("\n--- Priority vs Description Missingness ---")
priority_audit = pd.crosstab(
    df_events['priority'], 
    df_events['description_missing'], 
    normalize='columns'
) * 100
print(priority_audit)

--- Road Closure vs Description Missingness ---
description_missing      False      True
requires_road_closure
False                  69.0625  70.967742
True                   30.9375  29.032258

--- Priority vs Description Missingness ---
description_missing     False     True
priority
High                 56.71875  54.83871
Low                  43.28125  45.16129

In [33]:
valid_descriptions = df_events['description'].dropna().astype(str)

unique_count = valid_descriptions.nunique()
total_non_null = len(valid_descriptions)
print(f"Total non-null descriptions: {total_non_null}")
print(f"Unique descriptions: {unique_count} ({(unique_count / total_non_null) * 100:.1f}% unique)\n")

avg_length = valid_descriptions.str.len().mean()
median_length = valid_descriptions.str.len().median()
print(f"Average description length: {avg_length:.1f} characters")
print(f"Median description length: {median_length:.1f} characters\n")

# 3. Sample 20-30 descriptions
print("--- Sample of 20 Descriptions ---")
sample_desc = valid_descriptions.sample(n=min(20, total_non_null), random_state=42)
for i, desc in enumerate(sample_desc, start=1):
    print(f"{i}. {desc}")

Total non-null descriptions: 640
Unique descriptions: 514 (80.3% unique)

Average description length: 67.8 characters
Median description length: 53.0 characters

--- Sample of 20 Descriptions ---
1. ಟ್ರಾಫಿಕ್ ಗೆ ಯಾವುದೇ [PERSON] ಇರುವುದಿಲ್ಲ ಹೆಬ್ಬಾಳ ಡೌನ್ ರಾಂಪ್ ದಿಂದ ಕೆಂಪಾಪುರ ಕಡೆಗೆ
2. [PERSON] procession start sir
3. [LOCATION] towards marathhalli and karthiknagara towards mahadevpura traffic movement will be slow due to metrostation work
4. [LOCATION] work Ganesh [PERSON] towards [LOCATION] service road [LOCATION]
5. ನಮಸ್ತೆ ಸರ್ ಒಳಚರಂಡಿ ಕಾಮಗಾರಿ ಮಾಡುವುದರಿಂದ ರೋಡನ್ನು ಕ್ಲೋಸ್ [LOCATION]
6. [LOCATION] construction
7. Road Restriction for PM Visit
8. karthiknagara towards [LOCATION] and karthiknagara towards marathhalli traffic movement will be slow due to [LOCATION] station piller work
9. [PERSON] junction to bhoopasandra bus stand traffic Slow moment sir
10. White topping work
11. ಶಿವರಾತ್ರಿ ಪ್ರಯುಕ್ತ ಜನ ಸೇರಿರುತ್ತಾರೆ
12. kptcl work progressing at varturu college, varturu ps vehicles slow movement.
13. Road work
14. White Topping work at Dr. [PERSON].
15. [PERSON] towards [LOCATION] work going on sir traffic will be towards kadubisenahalli slow moving sir 🙏
16. [LOCATION] towards [LOCATION] and karthiknagara towards marathhalli traffic movement will be slow due to metrostation work
17. NHAI WORK @KODIGEHALLI DOWN RAMP TOWARD [LOCATION] SIR
18. BBMP FOOT path work progress at ITPL main Road near [LOCATION].
19. BAKRID BANDOBASTH
20. ನಮಸ್ತೆ ಸರ್ ಹೆಣ್ಣೂರು ಬಾಗಲೂರು ಮುಖ್ಯ ರಸ್ತೆ ಕೆ ನಾರಾಯಣಪುರ ಜಂಕ್ಷನ್ ಮತ್ತು ಗೆದ್ದಲಹಳ್ಳಿ ಕೆಲಸ ನಡೆಯುತ್ತಿರುವುದರಿಂದ ರೋಡ್ ಕೆಲಸ ಟ್ರಾಫಿಕ್ ಸ್ಲೋ ಮೊಮೆಂಟ್ ಇರುತ್ತದೆ

In [34]:
df_events['description_missing'] = df_events['description'].isna()

cause_missingness = pd.crosstab(
    df_events['event_cause'], 
    df_events['description_missing'], 
    margins=True,            # Adds row and column totals
    margins_name='Total'
)

cause_missingness['%_missing_within_cause'] = (
    cause_missingness[True] / cause_missingness['Total']
) * 100

print(cause_missingness.sort_values(by=True, ascending=False))

#Decision:Keep the null as it is for now.Fill it later as nodescription to avoid inventing information.

description_missing  False  True  Total  %_missing_within_cause
event_cause
Total                  640    31    671                4.619970
construction           461    19    480                3.958333
public_event            78     6     84                7.142857
procession              69     3     72                4.166667
protest                 12     3     15               20.000000
vip_movement            20     0     20                0.000000

Investigating endlatitude and endlongitude

In [35]:
print(df_events[['latitude', 'longitude', 'endlatitude', 'endlongitude']].isna().sum())
print("\nPercentage of valid end coordinates:")
print(df_events['endlatitude'].notna().mean() * 100)

exact_matches = (df_events['latitude'] == df_events['endlatitude']) & (df_events['longitude'] == df_events['endlongitude'])
print(f"Exact coordinate matches: {exact_matches.sum()} rows ({exact_matches.mean() * 100:.2f}%)")

import numpy as np
def haversine_np(lon1, lat1, lon2, lat2):
    # Convert degrees to radians
    lon1, lat1, lon2, lat2 = map(np.radians, [lon1, lat1, lon2, lat2])
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = np.sin(dlat/2.0)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2.0)**2
    c = 2 * np.arcsin(np.sqrt(a))
    km = 6367 * c
    return km
df_valid_ends = df_events.dropna(subset=['endlatitude', 'endlongitude']).copy()
df_valid_ends['distance_km'] = haversine_np(
    df_valid_ends['longitude'], df_valid_ends['latitude'],
    df_valid_ends['endlongitude'], df_valid_ends['endlatitude']
)
print(df_valid_ends['distance_km'].describe())

span_by_type = df_valid_ends.groupby('event_type')['distance_km'].agg(['count', 'mean', 'max'])
print(span_by_type)

latitude         0
longitude        0
endlatitude     27
endlongitude    27
dtype: int64

Percentage of valid end coordinates:
95.97615499254843
Exact coordinate matches: 11 rows (1.64%)
count     644.000000
mean     5865.306187
std      4053.949067
min         0.000000
25%         0.548144
50%      8658.700536
75%      8667.146343
max      8676.221525
Name: distance_km, dtype: float64
            count         mean          max
event_type
planned       441  5363.316593  8674.928203
unplanned     203  6955.835303  8676.221525

In [36]:
#inspect the rows with the largest distances, you can sort your temporary DataFrame (df_valid_ends) in descending order based on the calculated distance_km column.

largest_distances = df_valid_ends.sort_values(by='distance_km', ascending=False)[
    ['latitude', 'longitude', 'endlatitude', 'endlongitude', 'distance_km']
]

largest_distances.head(10)

       latitude  longitude  endlatitude  endlongitude  distance_km
3673  13.001375  77.757643          0.0           0.0  8676.221525
5594  13.006259  77.757203          0.0           0.0  8676.200372
2991  13.004196  77.756901          0.0           0.0  8676.156563
1492  13.005142  77.755105          0.0           0.0  8675.967449
2442  13.045768  77.750202          0.0           0.0  8675.657856
4161  12.981243  77.750685          0.0           0.0  8675.359933
2353  12.960859  77.747713          0.0           0.0  8674.928203
2693  12.942489  77.747459          0.0           0.0  8674.801531
2447  12.942443  77.747360          0.0           0.0  8674.790594
2673  12.942451  77.747177          0.0           0.0  8674.770840

In [37]:
#find out exactly how many rows have both endlatitude and endlongitude set to exactly 0
zero_ends_count = ((df_events['endlatitude'] == 0) & (df_events['endlongitude'] == 0)).sum()

print(f"Number of rows with (endlatitude == 0) AND (endlongitude == 0): {zero_ends_count}")

Number of rows with (endlatitude == 0) AND (endlongitude == 0): 436

In [38]:
#Count valid end target(teating 0 as missing)
is_valid_end = (
    (df_events['endlatitude'] != 0) & 
    (df_events['endlongitude'] != 0) & 
    df_events['endlatitude'].notna() & 
    df_events['endlongitude'].notna()
)
valid_end_count = is_valid_end.sum()
print(f"Total rows with true valid end coordinates: {valid_end_count}")

df_events['has_valid_end'] = is_valid_end
cause_vs_end = pd.crosstab(
    df_events['event_cause'], 
    df_events['has_valid_end'], 
    margins=True, 
    margins_name="Total"
)
cause_vs_end = cause_vs_end.sort_values(by=True, ascending=False)
print(cause_vs_end)

Total rows with true valid end coordinates: 208
has_valid_end  False  True  Total
event_cause
Total            463   208    671
construction     352   128    480
public_event      45    39     84
procession        53    19     72
vip_movement       4    16     20
protest            9     6     15

In [39]:
df_events.drop(['endlatitude', 'endlongitude'], axis=1, inplace=True)
df_events.shape

(671, 15)

Drop endlatitude
Drop endlongitude

~69% unavailable
Only useful for a minority of events
Adds complexity without enough coverage

Audit address after this

In [40]:
print("--- Sample Addresses ---")
print(df_events['address'].dropna().sample(10, random_state=42).tolist())

# 2. Check overlap with 'corridor'
# See if the corridor string is simply a subset of the address text
corridor_overlap = df_events.apply(
    lambda r: str(r['corridor']).lower() in str(r['address']).lower() 
    if pd.notna(r['corridor']) and pd.notna(r['address']) else False, 
    axis=1
).mean() * 100

# 3. Check cardinality (uniqueness) comparison
print("\n--- Uniqueness Count ---")
print(f"Total rows: {len(df_events)}")
print(f"Unique addresses: {df_events['address'].nunique()}")
print(f"Unique corridors: {df_events['corridor'].nunique()}")
print(f"Unique police stations: {df_events['police_station'].nunique()}")
print(f"Percentage of addresses containing the corridor name: {corridor_overlap:.2f}%")

--- Sample Addresses ---
['Outer Ring Road, Karthik Nagar, Marathahalli, Bengaluru, Karnataka. Pin-560037 (India)', 'Outer Ring Road, LRDE Employee Housing Colony, Karthik Nagar, Marathahalli, Bengaluru, Karnataka. Pin-560037 (India)', 'Bellary Road, TP Venugopal Layout, Anand Nagar, Hebbal, Bengaluru, Karnataka. Pin-560024 (India)', 'Rajatha Bhavana Road, Dr GP Rajarathnam Circle, Jalahalli, Bengaluru, Karnataka. Pin-560013 (India)', 'Kaithota, Bengaluru East City Corporation, Bengaluru, Bangalore East, Bengaluru Urban, Karnataka, 560066, India', '3rd Cross Road, Pattanagere Nagar, Sunkadakatte, Bengaluru, Karnataka. Pin-560091 (India)', 'Outer Ring Road, Karthik Nagar, Marathahalli, Bengaluru, Karnataka. Pin-560037 (India)', '2nd Main Road, Abdul Patel Syed Layout, Bhoopasandra, RMV Stage 2, Bengaluru, Karnataka. Pin-560094 (India)', 'Veeranapalaya Main Road, Govind Pura, Nagavara, Bengaluru, Karnataka. Pin-560045 (India)', 'Hennur Main Road, Muniswamappa Layout, Sangam Enclave, Kothnur Narayanapura, Bengaluru, Karnataka. Pin-560077 (India)']

--- Uniqueness Count ---
Total rows: 671
Unique addresses: 425
Unique corridors: 22
Unique police stations: 54
Percentage of addresses containing the corridor name: 2.38%

In [41]:
df_audit = df_events.copy()
null_counts = df_audit.isna().sum()
null_percentages = (df_audit.isna().mean() * 100).round(2)

final_audit = pd.DataFrame({
    'Missing Count': null_counts,
    'Percentage (%)': null_percentages
}).sort_values(by='Missing Count', ascending=False)

# Display the final report
print("--- Final Dataset Null-Value Audit ---")
print(final_audit)

--- Final Dataset Null-Value Audit ---
                       Missing Count  Percentage (%)
zone                              50            7.45
description                       31            4.62
address                            1            0.15
requires_road_closure              0            0.00
status                             0            0.00
event_type                         0            0.00
event_cause                        0            0.00
created_date                       0            0.00
priority                           0            0.00
longitude                          0            0.00
latitude                           0            0.00
corridor                           0            0.00
police_station                     0            0.00
description_missing                0            0.00
has_valid_end                      0            0.00

Audit:Status

In [42]:
print("--- Unique Status Values ---")
print(df_events['status'].unique())

print("\n--- Status Counts ---")
print(df_events['status'].value_counts())

print("\n--- Percentage Distribution ---")
print(df_events['status'].value_counts(normalize=True) * 100)

--- Unique Status Values ---
<StringArray>
['closed', 'active']
Length: 2, dtype: str

--- Status Counts ---
status
closed    598
active     73
Name: count, dtype: int64

--- Percentage Distribution ---
status
closed    89.120715
active    10.879285
Name: proportion, dtype: float64

In [43]:
closure_rate = df_events.groupby('status')['requires_road_closure'].mean()
print("--- Road Closure Rate by Status ---")
print(closure_rate)

priority_cross = pd.crosstab(df_events['status'], df_events['priority'], normalize='index') * 100
print("--- Priority Distribution within Status (%) ---")
print(priority_cross)

cause_cross = pd.crosstab(df_events['event_cause'], df_events['status'], normalize='index') * 100
print("--- Status Distribution by Event Cause (%) ---")
print(cause_cross)

--- Road Closure Rate by Status ---
status
active    0.287671
closed    0.311037
Name: requires_road_closure, dtype: float64
--- Priority Distribution within Status (%) ---
priority       High        Low
status
active    60.273973  39.726027
closed    56.187291  43.812709
--- Status Distribution by Event Cause (%) ---
status           active      closed
event_cause
construction  15.208333   84.791667
procession     0.000000  100.000000
protest        0.000000  100.000000
public_event   0.000000  100.000000
vip_movement   0.000000  100.000000

In [44]:
df_events.drop('status', axis=1, inplace=True)

# ==============================
# CREATED_DATE AUDIT (START HERE)
# ==============================

# Convert to datetime

In [45]:

df_events['created_date'] = pd.to_datetime(
    df_events['created_date'],
    errors='coerce'
)

print("Total Rows:", len(df_events))
print("Null Created_Date:", df_events['created_date'].isna().sum())
print("Invalid Timestamps (NaT):", df_events['created_date'].isna().sum())

print("\nMinimum Timestamp:")
print(df_events['created_date'].min())

print("\nMaximum Timestamp:")
print(df_events['created_date'].max())

print("\nUnique Years:")
print(sorted(df_events['created_date'].dt.year.dropna().unique()))

# Create fresh time-derived features
df_events['Year'] = df_events['created_date'].dt.year
df_events['Month'] = df_events['created_date'].dt.month
df_events['Day_of_Week'] = df_events['created_date'].dt.day_name()
df_events['Hour_of_Day'] = df_events['created_date'].dt.hour

print("\nHour Range:")
print("Min Hour =", df_events['Hour_of_Day'].min())
print("Max Hour =", df_events['Hour_of_Day'].max())

print("\nDay_of_Week Values:")
print(df_events['Day_of_Week'].unique())

Total Rows: 671
Null Created_Date: 0
Invalid Timestamps (NaT): 0

Minimum Timestamp:
2023-09-29 23:38:19.342539+00:00

Maximum Timestamp:
2024-04-07 21:12:00.747531+00:00

Unique Years:
[np.int32(2023), np.int32(2024)]

Hour Range:
Min Hour = 0
Max Hour = 23

Day_of_Week Values:
<StringArray>
['Tuesday', 'Thursday', 'Wednesday', 'Friday', 'Saturday', 'Sunday', 'Monday']
Length: 7, dtype: str

# ==================================
# DAY_OF_WEEK AUDIT
# ==================================

In [46]:
# 1. Event Volume by Day_of_Week
print("\n--- EVENT VOLUME BY DAY OF WEEK ---")
day_volume = df_events['Day_of_Week'].value_counts()
print(day_volume)

# 2. Road Closure Rate by Day_of_Week
print("\n--- ROAD CLOSURE RATE BY DAY OF WEEK ---")
closure_rate = (
    df_events.groupby('Day_of_Week')['requires_road_closure']
    .mean()
    .sort_values(ascending=False)
)
print((closure_rate * 100).round(2))

# 3. Priority Distribution by Day_of_Week
print("\n--- PRIORITY DISTRIBUTION BY DAY OF WEEK (%) ---")

priority_dist = (
    pd.crosstab(
        df_events['Day_of_Week'],
        df_events['priority'],
        normalize='index'
    ) * 100
).round(2)

print(priority_dist)

--- EVENT VOLUME BY DAY OF WEEK ---
Day_of_Week
Saturday     121
Tuesday      114
Wednesday     92
Thursday      91
Friday        91
Monday        84
Sunday        78
Name: count, dtype: int64

--- ROAD CLOSURE RATE BY DAY OF WEEK ---
Day_of_Week
Saturday     46.28
Sunday       41.03
Wednesday    31.52
Friday       26.37
Tuesday      25.44
Monday       22.62
Thursday     19.78
Name: requires_road_closure, dtype: float64

--- PRIORITY DISTRIBUTION BY DAY OF WEEK (%) ---

priority      High    Low
Day_of_Week
Friday       58.24  41.76
Monday       61.90  38.10
Saturday     50.41  49.59
Sunday       55.13  44.87
Thursday     54.95  45.05
Tuesday      55.26  44.74
Wednesday    63.04  36.96

In [47]:
print("\n--- EVENT CAUSE DISTRIBUTION BY DAY OF WEEK (%) ---")

cause_dist = (
    pd.crosstab(
        df_events['Day_of_Week'],
        df_events['event_cause'],
        normalize='index'
    ) * 100
).round(2)

print(cause_dist)

--- EVENT CAUSE DISTRIBUTION BY DAY OF WEEK (%) ---
event_cause  construction  procession  protest  public_event  vip_movement
Day_of_Week
Friday              78.02        5.49     1.10         14.29          1.10
Monday              58.33       28.57     1.19         11.90          0.00
Saturday            71.90        2.48     4.13          7.44         14.05
Sunday              51.28       19.23     0.00         29.49          0.00
Thursday            85.71        4.40     2.20          6.59          1.10
Tuesday             71.93       10.53     3.51         13.16          0.88
Wednesday           79.35        9.78     2.17          8.70          0.00

In [48]:
print("\n--- EVENT VOLUME BY HOUR ---")
print(df_events['Hour_of_Day'].value_counts().sort_index())

print("\n--- ROAD CLOSURE RATE BY HOUR (%) ---")
hour_closure = (
    df_events.groupby('Hour_of_Day')['requires_road_closure']
    .mean() * 100
).round(2)

print(hour_closure)

--- EVENT VOLUME BY HOUR ---
Hour_of_Day
0      46
1      15
2      27
3      29
4      50
5      56
6      30
7      16
8      14
9       4
10     19
11     17
12     16
13     10
16      2
17      1
18      7
19     32
20     80
21    108
22     39
23     53
Name: count, dtype: int64

--- ROAD CLOSURE RATE BY HOUR (%) ---
Hour_of_Day
0      43.48
1      20.00
2      29.63
3      37.93
4      36.00
5      35.71
6      46.67
7       6.25
8      14.29
9      75.00
10     78.95
11     70.59
12     62.50
13     30.00
16    100.00
17    100.00
18     71.43
19      6.25
20      7.50
21     15.74
22     20.51
23     49.06
Name: requires_road_closure, dtype: float64

In [49]:
print("\n--- EVENT CAUSE DISTRIBUTION BY HOUR (%) ---")

hour_cause = (
    pd.crosstab(
        df_events['Hour_of_Day'],
        df_events['event_cause'],
        normalize='index'
    ) * 100
).round(2)

print(hour_cause)

--- EVENT CAUSE DISTRIBUTION BY HOUR (%) ---
event_cause  construction  procession  protest  public_event  vip_movement
Hour_of_Day
0                   76.09       10.87     4.35          8.70          0.00
1                   40.00       13.33    13.33         26.67          6.67
2                   77.78       11.11     3.70          7.41          0.00
3                   58.62       20.69     0.00         20.69          0.00
4                   66.00       14.00     4.00         14.00          2.00
5                   55.36       23.21     1.79         19.64          0.00
6                   40.00       16.67     0.00         43.33          0.00
7                   37.50       25.00     6.25         31.25          0.00
8                   42.86       50.00     0.00          7.14          0.00
9                    0.00       25.00     0.00          0.00         75.00
10                  21.05        0.00     0.00         21.05         57.89
11                 100.00        0.00     0.00          0.00          0.00
12                  81.25        6.25     0.00          0.00         12.50
13                  50.00        0.00     0.00         50.00          0.00
16                 100.00        0.00     0.00          0.00          0.00
17                 100.00        0.00     0.00          0.00          0.00
18                  85.71       14.29     0.00          0.00          0.00
19                 100.00        0.00     0.00          0.00          0.00
20                  95.00        1.25     0.00          2.50          1.25
21                  84.26        7.41     3.70          3.70          0.93
22                  69.23       10.26     5.13         15.38          0.00
23                  73.58        7.55     0.00         18.87          0.00

In [50]:
print("\n--- EVENT VOLUME BY MONTH ---")
print(df_events['Month'].value_counts().sort_index())

print("\n--- ROAD CLOSURE RATE BY MONTH (%) ---")
month_closure = (
    df_events.groupby('Month')['requires_road_closure']
    .mean() * 100
).round(2)

print(month_closure)

--- EVENT VOLUME BY MONTH ---
Month
1     137
2     124
3     125
4      21
9       1
11     93
12    170
Name: count, dtype: int64

--- ROAD CLOSURE RATE BY MONTH (%) ---
Month
1      30.66
2      29.84
3      33.60
4      38.10
9     100.00
11     30.11
12     28.82
Name: requires_road_closure, dtype: float64

In [51]:
print("\n--- EVENT CAUSE DISTRIBUTION BY MONTH (%) ---")

month_cause = (
    pd.crosstab(
        df_events['Month'],
        df_events['event_cause'],
        normalize='index'
    ) * 100
).round(2)

print(month_cause)

--- EVENT CAUSE DISTRIBUTION BY MONTH (%) ---
event_cause  construction  procession  protest  public_event  vip_movement
Month
1                   78.83        6.57     2.19         11.68          0.73
2                   70.16       12.90     3.23         12.90          0.81
3                   67.20        8.80     2.40          8.80         12.80
4                   66.67        9.52     0.00         23.81          0.00
9                    0.00        0.00     0.00        100.00          0.00
11                  65.59       13.98     3.23         16.13          1.08
12                  74.12       12.35     1.18         11.76          0.59

In [52]:
print("\n--- TOTAL EVENT VOLUME BY YEAR ---")
print(df_events['Year'].value_counts().sort_index())

print("\n--- CLOSURE PERCENTAGES BY YEAR ---")
year_closure = (
    df_events.groupby('Year')['requires_road_closure']
    .mean() * 100
).round(2)

print(year_closure)

print("\n--- EVENT CAUSE DISTRIBUTION BY YEAR (%) ---")

year_cause = (
    pd.crosstab(
        df_events['Year'],
        df_events['event_cause'],
        normalize='index'
    ) * 100
).round(2)

print(year_cause)

--- TOTAL EVENT VOLUME BY YEAR ---
Year
2023    264
2024    407
Name: count, dtype: int64

--- CLOSURE PERCENTAGES BY YEAR ---
Year
2023    29.55
2024    31.70
Name: requires_road_closure, dtype: float64

--- EVENT CAUSE DISTRIBUTION BY YEAR (%) ---
event_cause  construction  procession  protest  public_event  vip_movement
Year
2023                70.83       12.88     1.89         13.64          0.76
2024                71.99        9.34     2.46         11.79          4.42

# ==================================
# DROP REJECTED DATETIME FEATURES
# ==================================

In [53]:
df_events = df_events.drop(
    columns=[
        'Hour_of_Day',
        'Month',
        'Year'
    ]
)

print(df_events.shape)
print(df_events.columns.tolist())

(671, 15)
['event_type', 'event_cause', 'description', 'requires_road_closure', 'priority', 'created_date', 'latitude', 'longitude', 'address', 'corridor', 'zone', 'police_station', 'description_missing', 'has_valid_end', 'Day_of_Week']

# ==================================
# DROP RAW TIMESTAMP
# ==================================

In [54]:
df_events = df_events.drop(columns=['created_date'])

print(df_events.shape)
print(df_events.columns.tolist())

(671, 14)
['event_type', 'event_cause', 'description', 'requires_road_closure', 'priority', 'latitude', 'longitude', 'address', 'corridor', 'zone', 'police_station', 'description_missing', 'has_valid_end', 'Day_of_Week']

In [55]:
print("\n--- HAS_VALID_END DISTRIBUTION ---")
print(df_events['has_valid_end'].value_counts())

print("\n--- ROAD CLOSURE RATE BY HAS_VALID_END ---")
print(
    df_events.groupby('has_valid_end')['requires_road_closure']
    .mean()
    .mul(100)
    .round(2)
)

print("\n--- PRIORITY DISTRIBUTION BY HAS_VALID_END (%) ---")
print(
    pd.crosstab(
        df_events['has_valid_end'],
        df_events['priority'],
        normalize='index'
    ).mul(100).round(2)
)

--- HAS_VALID_END DISTRIBUTION ---
has_valid_end
False    463
True     208
Name: count, dtype: int64

--- ROAD CLOSURE RATE BY HAS_VALID_END ---
has_valid_end
False     0.00
True     99.52
Name: requires_road_closure, dtype: float64

--- PRIORITY DISTRIBUTION BY HAS_VALID_END (%) ---
priority        High    Low
has_valid_end
False          61.12  38.88
True           46.63  53.37

# ==================================
# DROP LEAKAGE FEATURE
# ==================================

In [56]:


df_events = df_events.drop(columns=['has_valid_end'])

print(df_events.shape)
print(df_events.columns.tolist())

(671, 13)
['event_type', 'event_cause', 'description', 'requires_road_closure', 'priority', 'latitude', 'longitude', 'address', 'corridor', 'zone', 'police_station', 'description_missing', 'Day_of_Week']

In [57]:
print("\n--- PRIORITY DISTRIBUTION ---")
print(df_events['priority'].value_counts())

print("\n--- ROAD CLOSURE RATE BY PRIORITY (%) ---")
print(
    df_events.groupby('priority')['requires_road_closure']
    .mean()
    .mul(100)
    .round(2)
)

print("\n--- PRIORITY BY EVENT CAUSE (%) ---")
print(
    pd.crosstab(
        df_events['event_cause'],
        df_events['priority'],
        normalize='index'
    ).mul(100).round(2)
)

--- PRIORITY DISTRIBUTION ---
priority
High    380
Low     291
Name: count, dtype: int64

--- ROAD CLOSURE RATE BY PRIORITY (%) ---
priority
High    25.26
Low     38.14
Name: requires_road_closure, dtype: float64

--- PRIORITY BY EVENT CAUSE (%) ---
priority       High    Low
event_cause
construction  62.92  37.08
procession    31.94  68.06
protest       40.00  60.00
public_event  50.00  50.00
vip_movement  35.00  65.00

In [58]:
print(df_events[['priority']].head(20))
print(df_master.columns.tolist())

    priority
8       High
40      High
45       Low
52      High
82      High
113     High
125      Low
139     High
158     High
166     High
192      Low
199     High
216      Low
220      Low
229     High
235     High
241     High
253      Low
286     High
288      Low
['event_type', 'event_cause', 'description', 'requires_road_closure', 'status', 'priority', 'start_datetime', 'end_datetime', 'created_date', 'closed_datetime', 'resolved_datetime', 'latitude', 'longitude', 'endlatitude', 'endlongitude', 'end_address', 'address', 'corridor', 'junction', 'zone', 'direction', 'police_station']

In [59]:
pd.crosstab(
    df_events['event_cause'],
    df_events['event_type'],
    margins=True
)

event_type    planned  unplanned  All
event_cause
construction      311        169  480
procession         38         34   72
protest             8          7   15
public_event       84          0   84
vip_movement       20          0   20
All               461        210  671

In [60]:
df_events.groupby('event_cause')['event_type'].nunique().sort_values()

event_cause
public_event    1
vip_movement    1
procession      2
construction    2
protest         2
Name: event_type, dtype: int64

In [61]:
df_events.groupby('event_type')['event_cause'].nunique().sort_values()

event_type
unplanned    3
planned      5
Name: event_cause, dtype: int64

In [62]:
pd.crosstab(
    df_events['event_type'],
    df_events['requires_road_closure'],
    normalize='index'
) * 100

requires_road_closure      False      True
event_type
planned                63.774403  36.225597
unplanned              80.952381  19.047619

In [63]:
print(df_events.columns.tolist())

['event_type', 'event_cause', 'description', 'requires_road_closure', 'priority', 'latitude', 'longitude', 'address', 'corridor', 'zone', 'police_station', 'description_missing', 'Day_of_Week']

In [64]:
df_events.to_csv("cleaned_astram_event_data_final.csv", index=False)

In [65]:
y = df_events['requires_road_closure']
X = df_events.drop(columns=['requires_road_closure'])

In [66]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

In [67]:
print(X_train.shape)
print(X_test.shape)
print(y_train.value_counts(normalize=True))
print(y_test.value_counts(normalize=True))

(536, 12)
(135, 12)
requires_road_closure
False    0.692164
True     0.307836
Name: proportion, dtype: float64
requires_road_closure
False    0.688889
True     0.311111
Name: proportion, dtype: float64

In [68]:
text_features = ['description']

categorical_features = [
    'event_type',
    'event_cause',
    'priority',
    'address',
    'corridor',
    'zone',
    'police_station',
    'Day_of_Week'
]

numeric_features = [
    'latitude',
    'longitude',
    'description_missing'
]

In [69]:
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        ('text', TfidfVectorizer(
            max_features=200,
            stop_words='english'
        ), 'description'),

        ('cat', OneHotEncoder(
            handle_unknown='ignore'
        ), categorical_features),

        ('num', 'passthrough', numeric_features)
    ]
)

In [70]:
X_train['description'] = X_train['description'].fillna('No Description')
X_test['description'] = X_test['description'].fillna('No Description')

In [71]:
print(X_train['description'].isna().sum())
print(X_test['description'].isna().sum())

0
0

In [72]:
X_train_transformed = preprocessor.fit_transform(X_train)

print(X_train_transformed.shape)

(536, 663)

In [73]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

baseline_model = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(
        max_iter=1000,
        random_state=42
    ))
])

baseline_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('text',
                                                  TfidfVectorizer(max_features=200,
                                                                  stop_words='english'),
                                                  'description'),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['event_type', 'event_cause',
                                                   'priority', 'address',
                                                   'corridor', 'zone',
                                                   'police_station',
                                                   'Day_of_Week']),
                                                 ('num', 'passthrough',
                                                  ['latitude', 'longitude',
                                                   'description_missing'])])),
                ('classifier',
                 LogisticRegression(max_iter=1000, random_state=42))])

In [74]:
from sklearn.metrics import classification_report

y_pred = baseline_model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.79      0.92      0.85        93
        True       0.73      0.45      0.56        42

    accuracy                           0.78       135
   macro avg       0.76      0.69      0.71       135
weighted avg       0.77      0.78      0.76       135

In [75]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

rf_model = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(
        n_estimators=300,
        random_state=42,
        class_weight='balanced'
    ))
])

rf_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('text',
                                                  TfidfVectorizer(max_features=200,
                                                                  stop_words='english'),
                                                  'description'),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['event_type', 'event_cause',
                                                   'priority', 'address',
                                                   'corridor', 'zone',
                                                   'police_station',
                                                   'Day_of_Week']),
                                                 ('num', 'passthrough',
                                                  ['latitude', 'longitude',
                                                   'description_missing'])])),
                ('classifier',
                 RandomForestClassifier(class_weight='balanced',
                                        n_estimators=300, random_state=42))])

In [76]:
rf_pred = rf_model.predict(X_test)
print(classification_report(y_test, rf_pred))

              precision    recall  f1-score   support

       False       0.79      0.95      0.86        93
        True       0.78      0.43      0.55        42

    accuracy                           0.79       135
   macro avg       0.78      0.69      0.71       135
weighted avg       0.78      0.79      0.76       135

In [77]:
import xgboost
print(xgboost.__version__)

3.2.0

In [78]:
from xgboost import XGBClassifier
from sklearn.pipeline import Pipeline

xgb_model = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', XGBClassifier(
        n_estimators=300,
        max_depth=5,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        scale_pos_weight=464/207,
        random_state=42,
        eval_metric='logloss'
    ))
])

xgb_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('text',
                                                  TfidfVectorizer(max_features=200,
                                                                  stop_words='english'),
                                                  'description'),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['event_type', 'event_cause',
                                                   'priority', 'address',
                                                   'corridor', 'zone',
                                                   'police_station',
                                                   'Day_of_Week']),
                                                 ('num', 'passthrough',
                                                  ['latitude', 'longitude',
                                                   'description_miss...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=5, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [79]:
from sklearn.metrics import classification_report

xgb_pred = xgb_model.predict(X_test)

print(classification_report(y_test, xgb_pred))

              precision    recall  f1-score   support

       False       0.82      0.84      0.83        93
        True       0.62      0.60      0.61        42

    accuracy                           0.76       135
   macro avg       0.72      0.72      0.72       135
weighted avg       0.76      0.76      0.76       135

In [80]:
from sklearn.metrics import roc_auc_score

xgb_probs = xgb_model.predict_proba(X_test)[:,1]

auc = roc_auc_score(y_test, xgb_probs)

print("ROC-AUC:", auc)

ROC-AUC: 0.7946748591909882

In [81]:
xgb_clf = xgb_model.named_steps['classifier']

importances = xgb_clf.feature_importances_

feature_names = xgb_model.named_steps[
    'preprocessor'
].get_feature_names_out()

importance_df = (
    pd.DataFrame({
        'feature': feature_names,
        'importance': importances
    })
    .sort_values('importance', ascending=False)
)

print(importance_df.head(20))

                                               feature  importance
116                                      text__traffic    0.039251
581                          cat__corridor_ORR North 2    0.028688
200                            cat__event_type_planned    0.021861
638                         cat__police_station_Peenya    0.018425
155                                           text__ತದ    0.018298
103                                         text__slow    0.016938
336  cat__address_HAL Airport Road, Marathahalli, B...    0.016270
201                          cat__event_type_unplanned    0.015068
175                                           text__ಯಲ    0.015048
100                                      text__service    0.014651
579                           cat__corridor_ORR East 2    0.014637
13                                        text__bridge    0.014209
2                                        text__airport    0.014014
590                              cat__zone_East Zone 1    0.012806
68                                      text__movement    0.012412
640                     cat__police_station_R.T. Nagar    0.011957
586                         cat__corridor_Varthur Road    0.011578
80                                        text__person    0.011388
92                                          text__ramp    0.011252
128                                      text__working    0.011010

In [82]:
df_events[
    df_events['description']
    .fillna('')
    .str.contains('traffic', case=False, na=False)
][['description', 'requires_road_closure']].head(20)

                                            description  requires_road_closure
52    [LOCATION] towards marathhalli and karthiknaga...                  False
82    karthiknagara towards [LOCATION] and karthikna...                  False
139   [LOCATION] towards marathhalli and karthiknaga...                  False
235   [LOCATION] towards marathhalli and karthiknaga...                  False
312   [LOCATION] towards marathhalli and karthiknaga...                  False
337         [PERSON] working in progress traffic normal                  False
478   [PERSON] junction to bhoopasandra bus stand tr...                  False
553   karthiknagara towards [LOCATION] and karthikna...                  False
561   [LOCATION] work going on Sir traffic is slow m...                  False
629   [LOCATION] towards [PERSON] and [PERSON] towar...                  False
690   BWSSB work at [LOCATION] hebbal circle to bhad...                  False
805   [LOCATION] towards [PERSON] and [PERSON] towar...                  False
816                      road construction...no traffic                   True
857   kptcl work at panattur main road towards kadub...                  False
905   KPTCL Cable work progressing at panattur railw...                  False
934   [LOCATION] to Kadabeesanahalli. Infront of [PE...                  False
956   due to [LOCATION] festival outgoing and  incom...                  False
970   karthiknagara towards [LOCATION] and karthikna...                  False
1014  [PERSON] station work traffic slow moment sir ...                  False
1025  karthiknagara towards [LOCATION] and karthikna...                  False

In [83]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, xgb_pred))

[[78 15]
 [17 25]]

In [84]:
from backend.recommendation_engine import generate_recommendations

In [85]:
print(generate_recommendations(0.75, "procession"))

{'Road Closure': 'Yes', 'Police Deployment': 'High', 'Barricades': 'Required', 'Diversion': 'Required', 'Closure Probability': 0.75}

In [86]:
print(
    importance_df[
        importance_df["feature"]
        .str.contains("priority", case=False)
    ]
)

                feature  importance
208   cat__priority_Low    0.008245
207  cat__priority_High    0.006738

#Saving Model

In [87]:
import joblib

joblib.dump(xgb_model, "road_closure_model.pkl")

print("Model saved successfully!")

Model saved successfully!

In [88]:
print(df_events["corridor"].value_counts().head(20))

corridor
Non-corridor              291
ORR East 2                102
ORR North 1                39
Mysore Road                30
Bellary Road 2             24
Airport New South Road     23
ORR East 1                 18
Bellary Road 1             18
Magadi Road                16
Old Madras Road            15
Hennur Main Road           14
ORR North 2                14
Old Airport Road           11
Varthur Road                9
ORR West 1                  9
CBD 2                       7
IRR(Thanisandra road)       7
West of Chord Road          7
Bannerghata Road            6
Tumkur Road                 5
Name: count, dtype: int64